### ISSUE TITLE
srtp-cvs will not build in 0.5.4 / linux

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yss163com/libjingle#165]
```
What steps will reproduce the problem?
1. Run $path_to_swtoolkit/hammer.sh

What is the expected output? What do you see instead?
I expect libjingle-0.5.4 and its third party dependencies build. Instead, srtp 
fails with the following: 

third_party/srtp/srtp/ekt.c: In function 'srtp_stream_init_from_ekt':
third_party/srtp/srtp/ekt.c:169:12: error: variable 'master_key_len' set but 
not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

scons: *** [build/dbg/obj/third_party/srtp/srtp/ekt.o] Error 1
scons: building terminated because of errors.

What version of the product are you using? On what operating system?
I am using libjingle-0.5.4, srtp-cvs from this site, and I'm running Arch Linux 
(x86_64). 

Please provide any additional information below.
My system is up to date and all the tools and env variables appear to be set 
right. SRTP simply has a bug; will try with other versions but the zip file 
available under Downloads does not build. 

```

Original issue reported on code.google.com by `roken...@gmail.com` on 15 May 2011 at 11:18
