### ISSUE TITLE
unused variable in ipaddress.cc breaks build on gcc 4.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yss163com/libjingle#304]
```
What steps will reproduce the problem?
1. Try to build libjingle with gcc 4.6
2.
3.

What is the expected output? What do you see instead?

________Compiling build/dbg/obj/base/ipaddress.o
base/ipaddress.cc: In function ‘talk_base::IPAddress 
talk_base::TruncateIP(const talk_base::IPAddress&, int)’:
base/ipaddress.cc:327:14: error: variable ‘ip_addr’ set but not used 
[-Werror=unused-but-set-variable]
cc1plus: all warnings being treated as errors

scons: *** [build/dbg/obj/base/ipaddress.o] Error 1


What version of the product are you using? On what operating system?
r110 and beyond, Fedora 16, gcc 4.6.2.

Please provide any additional information below.

See patch.
```

Original issue reported on code.google.com by `bprodo...@connectify.me` on 17 Feb 2012 at 3:09

Attachments:
- [003-ipaddress-fix.patch](https://storage.googleapis.com/google-code-attachments/libjingle/issue-304/comment-0/003-ipaddress-fix.patch)
