### ISSUE TITLE
doesn't compile with gcc 4.6 (with default of warnings treated as errors)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yss163com/libjingle#252]
```
What steps will reproduce the problem?
1. try to compile libjingle with gcc 4.6 without hacking up the build scripts 
to disable warnings-as-errors
2.
3.

What is the expected output? What do you see instead?
I expect a successful build.  Instead I get this:

________Compiling build/dbg/obj/third_party/srtp/srtp/ekt.o
third_party/srtp/srtp/ekt.c: In function ‘srtp_stream_init_from_ekt’:
third_party/srtp/srtp/ekt.c:169:12: error: variable ‘master_key_len’ set 
but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

What version of the product are you using? On what operating system?
r99, 32-bit Ubuntu 11.10

Please provide any additional information below.
$ gcc --version
gcc (Ubuntu/Linaro 4.6.1-9ubuntu3) 4.6.1
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Original issue reported on code.google.com by `bprodo...@connectify.me` on 7 Dec 2011 at 3:45
