### ISSUE TITLE
Does not build on Mac OS X 10.6 with gcc 4.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yss163com/libjingle#64]
```
What steps will reproduce the problem?
1. ./configure 
2. make
3. Build error

What is the expected output? What do you see instead?
Expected output is a libjingle library. Instead, I see:

 ../../talk/base/stringutils.h:272: error: extra qualification 'talk_base::Traits<char>::' on member 'empty_str'
socketadapters.cc: In member function 'void 
talk_base::AsyncHttpsProxySocket::ProcessLine(char*, size_t)':
socketadapters.cc:359: warning: use of assignment suppression and length 
modifier together in scanf format
socketadapters.cc:359: warning: use of assignment suppression and length 
modifier together in scanf format
make[3]: *** [socketadapters.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

What version of the product are you using? On what operating system?
libjingle 0.4 on Mac OS X 10.6, gcc 4.2


Please provide any additional information below.
I started correcting the errors but I imagine something is more fundamentally 
wrong. 

```

Original issue reported on code.google.com by `roken...@gmail.com` on 9 Sep 2010 at 3:37
