### ISSUE TITLE
Another missing include for gcc 4.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yss163com/libjingle#54]
```
Compiling libjingle as part of chromium using gcc 4.4 fails.

libjingle/files/talk/base/asynctcpsocket.cc:172: error: ‘strerror’ is not a 
member of ‘std’

See attached patch. I'm going to add this to the local copy of jingle in 
chromium.

Thanks!

PS. To be more technically correct, at the time of writing this 
asynctcpsocket.cc isn't part of the chromium build but it will be shortly at 
which point this error will happen in trunk builds with gcc 4.4.
```

Original issue reported on code.google.com by `craig.schlenter@chromium.org` on 2 Nov 2009 at 4:56

Attachments:
- [jingle.diff](https://storage.googleapis.com/google-code-attachments/libjingle/issue-54/comment-0/jingle.diff)
