### ISSUE TITLE
problem with pango library when compiling libjingle 0.5.8 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yss163com/libjingle#188]
```
I'm new user, so please forgive me any mistakes.

I tried to compile libjigle with GTK+2-2.18.9;

When using pango 1.22:
[...]
scons: Building targets ...
scons: `all_libraries' is up to date.
________Linking build/dbg/obj/login
________Linking build/dbg/obj/call
build/dbg/lib/libvideorenderer.a(gtkvideorenderer.o): In function 
`GtkVideoRenderer':
/root/libjingle-0.5.8/talk/session/phone/gtkvideorenderer.cc:41: undefined 
reference to `g_thread_init'
collect2: ld returned 1 exit status
scons: *** [build/dbg/obj/call] Error 1
scons: building terminated because of 


When using pango 1.28:
scons: Building targets ...
________Compiling build/dbg/obj/session/phone/gtkvideorenderer.o
________Creating library build/dbg/obj/libvideorenderer.a
________Indexing build/dbg/obj/libvideorenderer.a
Install file: "build/dbg/obj/libvideorenderer.a" as 
"build/dbg/lib/libvideorenderer.a"
________Linking build/dbg/obj/login
/usr/lib/libpangocairo-1.0.so.0: undefined reference to `g_malloc_n'
/usr/lib/libpango-1.0.so.0: undefined reference to `g_realloc_n'
/usr/lib/libpango-1.0.so.0: undefined reference to `g_malloc0_n'
collect2: ld returned 1 exit status
scons: *** [build/dbg/obj/login] Error 1
scons: building terminated because of errors.


I had two other versions of pango, but i always had one of above problems;

I'm working on Slackware Linux 13.0 32bit;

Thanks,
David
```

Original issue reported on code.google.com by `dawid.ja...@gmail.com` on 13 Jul 2011 at 1:32
