### ISSUE TITLE
0.6.9 does not compile on Linux (gcc 4.4)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yss163com/libjingle#274]
```
What steps will reproduce the problem?
1. try to compile on Linux with gcc 4.4

What is the expected output? What do you see instead?
Errors are as follows:

________Linking build/dbg/obj/call
build/dbg/lib/libvideorenderer.a(gtkvideorenderer.o): In function 
`GtkVideoRenderer':
/home/brianp/src/libjingle/google/builder/libjingle/talk/session/phone/gtkvideor
enderer.cc:53: undefined reference to `g_thread_init'

________Compiling build/dbg/obj/base/linux_unittest.o
base/linux_unittest.cc:32:32: error: testing/base/gunit.h: No such file or 
directory


What version of the product are you using? On what operating system?
SVN r106, Fedora 12.

Please provide any additional information below.
Patch provided.

```

Original issue reported on code.google.com by `bprodo...@connectify.me` on 11 Jan 2012 at 4:19

Attachments:
- [linux-compile-fixes.patch](https://storage.googleapis.com/google-code-attachments/libjingle/issue-274/comment-0/linux-compile-fixes.patch)
